# Generated by Django 4.1.5 on 2023-01-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_institiute',
            new_name='is_institute',
        ),
    ]
