# Generated by Django 4.1.5 on 2023-01-20 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_institiute_accounts_is_institute'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_on', models.DateField(auto_now_add=True, null=True)),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=1500, null=True)),
                ('website', models.CharField(max_length=50, null=True)),
                ('about_video', models.FileField(null=True, upload_to='about_video')),
                ('institute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
